config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/formulario', to: 'contact#form', as: :my_form
  get '/destino', to: 'contact#destiny', as: :destiny

  post '/destino', to: 'contact#destiny', as: :post_destiny
  get '/fim', to: 'contact#final', as: :final
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def form
    end

    def destiny
        redirect_to final_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_myform.html.erb
<%= form_with url: post_destiny_path, class: 'my-form' do |f| %>
    <h1>Comece agora</h1>
    <h2>Como devemos te chamar ?</h2>
    <%= f.text_field :name %>
    <h2>Qual seu email ?</h2>
    <%= f.email_field :email %>
    <h2>Telefone</h2>
    <%= f.text_field :telefone %>
    <h2>Mensagem</h2>
    <%= f.text_field :msg %>
    <%= f.submit "Enviar" %>
<% end %>

app/views/contact/destiny.html.erb
<h1>Teste do get</h1>

app/views/contact/final.html.erb
<h1>Formulário enviado com exito</h1>

app/views/contact/form.html.erb
<h1>Formulário</h1>
<%= render 'myform'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula2Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>